apiVersion: v1
kind: Secret
metadata:
  name: {{ include "konsole-ai.fullname" . }}-api
  labels:
    {{- include "konsole-ai.labels" . | nindent 4 }}
type: Opaque
stringData:
  API_KEYS: {{ .Values.secrets.apiKeys | quote }}
